// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://charity.org/
// Generated: 2026-08-27T15:33:41.724Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#333333' | '#ffffff' | '#000000' | '#06333c' | '#15768d' | '#80bc2f' | '#eba92f' | '#6ec1e4' | '#d15e1e' | '#202020' | '#f1f1f1' | '#ff0000' | '#2e9935' | '#80bc00' | '#772583';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Montserrat' | 'Times New Roman' | 'turbinado-pro' | 'eicons';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '700' | '900' | '500' | '800';

export type SpacingToken = '1px' | '30px' | '34px' | '38px' | '46px' | '60px' | '64px' | '68px' | '75px' | '78px' | '84px' | '90px' | '134px' | '160px' | '264px';

export type RadiusToken = '3px' | '7px' | '10px' | '25px' | '34px' | '50px';

export type DurationToken = '200ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
